sudo: required

services:
  - docker

language: go

go:
  - "1.12"
  - "1.13"
  - "1.14"
  - "1.15"

script: make unit && make integration

jobs:
  include:
    - stage: check
      install: go get golang.org/x/lint/golint github.com/kisielk/errcheck
      script: make lint && make errcheck
      go: "1.15" # only run source code analysis tools on latest version of Go