sudo: required

services:
    - docker

language: go

go:
    - 1.9
    - "1.10"
    - tip

before_install:
    - docker pull andyrbell/mountebank:1.14.0
    - make tools

script:
    - make lint
    - make errcheck
    - make vet
    - make test
