sudo: required

services:
    - docker

language: go

go:
    - 1.6
    - 1.7
    - 1.8
    - 1.9
    - "1.10"
    - tip

before_install:
    - make tools

script:
    - make vet
    - make lint
    - make errcheck
    - make test
