sudo: required

services:
    - docker

language: go

go:
    - "1.10"
    - "1.11"
    - "1.12"

jobs:
    include:
        - stage: test
          before_install:
              - docker run -d --rm --name=mountebank -p 2525:2525 -p 8080:8080 -p 8081:8081 andyrbell/mountebank:2.0.0
          script:
              - make integration
          # only run source code analysis tools on latest version of Go
        - stage: check
          go: "1.12"
          before_install:
              - go get golang.org/x/lint/golint
              - go get github.com/kisielk/errcheck
          script:
              - make lint
              - make errcheck
