sudo: required

services:
    - docker

language: go

go:
    - 1.9
    - "1.10"
    - "1.11"
    - tip

before_install:
    - make pull
    - make tools

script:
    - make errcheck
    - make lint
    - make integration
